# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: info_checker.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'info_checker.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12info_checker.proto\x12\x0cinfo_checker\"P\n\x0c\x43heckRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x14\n\x0c\x63ustom_rules\x18\x02 \x03(\t\x12\x1c\n\x14similarity_threshold\x18\x03 \x01(\x01\"\x8a\x01\n\rCheckResponse\x12\x14\n\x0cis_sensitive\x18\x01 \x01(\x08\x12-\n\x07matches\x18\x02 \x03(\x0b\x32\x1c.info_checker.SensitiveMatch\x12\x1a\n\x12overall_risk_level\x18\x03 \x01(\t\x12\x18\n\x10\x63onfidence_score\x18\x04 \x01(\x01\"\xa4\x01\n\x0eSensitiveMatch\x12\x12\n\nmatch_type\x18\x01 \x01(\t\x12\x11\n\trule_name\x18\x02 \x01(\t\x12\x14\n\x0cmatched_text\x18\x03 \x01(\t\x12\x12\n\nconfidence\x18\x04 \x01(\x01\x12\x16\n\x0estart_position\x18\x05 \x01(\x05\x12\x14\n\x0c\x65nd_position\x18\x06 \x01(\x05\x12\x13\n\x0b\x65xplanation\x18\x07 \x01(\t\"A\n\x11\x42\x61tchCheckRequest\x12,\n\x08requests\x18\x01 \x03(\x0b\x32\x1a.info_checker.CheckRequest\"D\n\x12\x42\x61tchCheckResponse\x12.\n\tresponses\x18\x01 \x03(\x0b\x32\x1b.info_checker.CheckResponse\"%\n\x12HealthCheckRequest\x12\x0f\n\x07service\x18\x01 \x01(\t\"\xa3\x01\n\x13HealthCheckResponse\x12?\n\x06status\x18\x01 \x01(\x0e\x32/.info_checker.HealthCheckResponse.ServingStatus\x12\x0f\n\x07message\x18\x02 \x01(\t\":\n\rServingStatus\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07SERVING\x10\x01\x12\x0f\n\x0bNOT_SERVING\x10\x02\x32\xf8\x01\n\x0bInfoChecker\x12\x44\n\tCheckText\x12\x1a.info_checker.CheckRequest\x1a\x1b.info_checker.CheckResponse\x12O\n\nCheckBatch\x12\x1f.info_checker.BatchCheckRequest\x1a .info_checker.BatchCheckResponse\x12R\n\x0bHealthCheck\x12 .info_checker.HealthCheckRequest\x1a!.info_checker.HealthCheckResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'info_checker_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHECKREQUEST']._serialized_start=36
  _globals['_CHECKREQUEST']._serialized_end=116
  _globals['_CHECKRESPONSE']._serialized_start=119
  _globals['_CHECKRESPONSE']._serialized_end=257
  _globals['_SENSITIVEMATCH']._serialized_start=260
  _globals['_SENSITIVEMATCH']._serialized_end=424
  _globals['_BATCHCHECKREQUEST']._serialized_start=426
  _globals['_BATCHCHECKREQUEST']._serialized_end=491
  _globals['_BATCHCHECKRESPONSE']._serialized_start=493
  _globals['_BATCHCHECKRESPONSE']._serialized_end=561
  _globals['_HEALTHCHECKREQUEST']._serialized_start=563
  _globals['_HEALTHCHECKREQUEST']._serialized_end=600
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=603
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=766
  _globals['_HEALTHCHECKRESPONSE_SERVINGSTATUS']._serialized_start=708
  _globals['_HEALTHCHECKRESPONSE_SERVINGSTATUS']._serialized_end=766
  _globals['_INFOCHECKER']._serialized_start=769
  _globals['_INFOCHECKER']._serialized_end=1017
# @@protoc_insertion_point(module_scope)
