# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import info_checker_pb2 as info__checker__pb2

GRPC_GENERATED_VERSION = '1.75.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in info_checker_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class InfoCheckerStub(object):
    """Service definition for checking sensitive information
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CheckText = channel.unary_unary(
                '/info_checker.InfoChecker/CheckText',
                request_serializer=info__checker__pb2.CheckRequest.SerializeToString,
                response_deserializer=info__checker__pb2.CheckResponse.FromString,
                _registered_method=True)
        self.CheckBatch = channel.unary_unary(
                '/info_checker.InfoChecker/CheckBatch',
                request_serializer=info__checker__pb2.BatchCheckRequest.SerializeToString,
                response_deserializer=info__checker__pb2.BatchCheckResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/info_checker.InfoChecker/HealthCheck',
                request_serializer=info__checker__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=info__checker__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class InfoCheckerServicer(object):
    """Service definition for checking sensitive information
    """

    def CheckText(self, request, context):
        """Check a single text for sensitive content
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckBatch(self, request, context):
        """Batch check multiple texts
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check for service availability
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InfoCheckerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CheckText': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckText,
                    request_deserializer=info__checker__pb2.CheckRequest.FromString,
                    response_serializer=info__checker__pb2.CheckResponse.SerializeToString,
            ),
            'CheckBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckBatch,
                    request_deserializer=info__checker__pb2.BatchCheckRequest.FromString,
                    response_serializer=info__checker__pb2.BatchCheckResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=info__checker__pb2.HealthCheckRequest.FromString,
                    response_serializer=info__checker__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'info_checker.InfoChecker', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('info_checker.InfoChecker', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class InfoChecker(object):
    """Service definition for checking sensitive information
    """

    @staticmethod
    def CheckText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/info_checker.InfoChecker/CheckText',
            info__checker__pb2.CheckRequest.SerializeToString,
            info__checker__pb2.CheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/info_checker.InfoChecker/CheckBatch',
            info__checker__pb2.BatchCheckRequest.SerializeToString,
            info__checker__pb2.BatchCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/info_checker.InfoChecker/HealthCheck',
            info__checker__pb2.HealthCheckRequest.SerializeToString,
            info__checker__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
